### ISSUE TITLE
Make ingress path configurable for litmus-2-0-0-beta

### ISSUE THREAD

**Issue by itustanic** [litmuschaos/litmus-helm#138]
I would make a PR for this however I want to know if it is a good idea.

My team has been working to install Litmus on our system. We went with trying the Litmus Portal which is of course packaged into the litmus-2-0-0-beta helm package.

However, after setting up the ingress, we noticed that the path is not configurable. The path is by default set to /(star), however our team usually just sets the path to "/". I had to manually install the helm charts on our local repository and point the helm chart to our configuration to delete the extra (star), to get it working properly on our end.

Usually, this path field is configurable. I'm wondering if I can open a PR to patch this variable and make it configurable, or is there some reason that /(star) is the default path for the ingress currently that is hardcoded?

Thanks.

**Comment by Jasstkn** [comment]
Hello @itustanic! Thank you for your feedback! Please, make a contribution if you have time =) It will be highly appreciated!
