### ISSUE TITLE
Mongo StatefulSet doesn't set correct security context

### ISSUE THREAD

**Issue by Niksko** [litmuschaos/litmus-helm#140]
The Mongo DB StatefulSet pod doesn't set the correct security context parameters. This means that even if you have configured it to use a service account, and have set up the correct PSP, the PSP may not be chosen because the pod doesn't declare that it needs to run as non root, and that it needs `CAP_CHOWN`, `CAP_SETUID` and `CAP_SETGID`.

**Comment by Jasstkn** [comment]
we removed internal DB, now you can control values for bitnami's helm-chart via values or use your own database that is deployed outside of this helm-chart.
