### ISSUE TITLE
Question: How to set NodeSelector for agent plane resources using helm chart? 

### ISSUE THREAD

**Issue by nosmolovskiy** [litmuschaos/litmus-helm#163]
I want to run agent plane(subscriber, event-tracker, litmus-operator-ce, workflow-controller) resources on particular nodes.
I found that these resources can be executed with node selector([litmuschaos/litmus](https://github.com/litmuschaos/litmus/blob/master/litmus-portal/graphql-server/manifests/cluster/1d_argo_deployment.yaml#L30)) but cant get how to do it using chart.
Do someone can help?

**Comment by nosmolovskiy** [comment]
@rajdas98 thanks for answer.
After login to portal I see that  Self-Agent was installed to cluster.
Is it possible set NodeSelector for subscriber, chaos-operator-ce, chaos-exporter and  workflow-controller which were installed as 
Self-Agent  using helm chart?

**Comment by rajdas98** [comment]
for self-agent, node-selector flag is not installed.

You can disconnect the self-agent and reconnect it using litmusctl(with --node-selector flag).

**Comment by nosmolovskiy** [comment]
thanks @rajdas98

**Comment by sthomson-wyn** [comment]
For future readers, this appears to now be possible declaratively via https://github.com/litmuschaos/litmus/pull/3527

**Comment by emmahsax** [comment]
@sthomson-wyn You mentioned node selectors and tolerations can be declaratively added. Can you explain what you mean? Is there a way for me to set the tolerations, node selectors, and resources via helm?

I see mention of the chaos-exporter, chaos-operator, subscriber, etc here: https://github.com/litmuschaos/litmus-helm/tree/master/charts/litmus-agent#requirements. Is that helm command how I set these values, or do I need to use litmusctl? Are there any docs around how to set those three values (tolerations, node selectors, resources) on the agent plane resources?
