### ISSUE TITLE
Add param in values to enable/disable google analytics

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus-helm#18]
- In Litmus, we collect the following usage metrics from the litmus deployments - (a) number of operator installations (b) run count of a particular experiment. 

- This is done in order to gather chaos trends that will help us to improve the project. 

- However, in some cases where there are compliance requirements or in air-gapped environments, it might be necessary to turn the GA off. 

- This is possible today via an ENV in the litmus chaos operator deployment: refer https://docs.litmuschaos.io/docs/faq-general/#does-litmus-track-any-usage-metrics-on-the-test-clusters

- This needs to be added a helm tunable, with default set to 'true'. For ex, in the operator: 

  ```yaml
  policies:
    monitoring:
      enabled: true
  ```

  With the env set to "FALSE" only when the operator.policies.monitoring.enabled is false.

**Comment by Jasstkn** [comment]
@ksatchit thanks, will create a PR for adding that.
