### ISSUE TITLE
Error on subscriber pod

### ISSUE THREAD

**Issue by luigi-bitonti** [litmuschaos/litmus-helm#182]
Hi guys, I experimented an error while I was trying to install a litmus environment with self signed certificated.
I used **gdsoumya/litmusportal-subscriber:ci** image and **SKIP_SSL_VERIFY : "true"** env var as suggest in a previous issue, but I see this logs from the pod: 

![image](https://user-images.githubusercontent.com/93377317/143591236-8ea89387-02f6-4f69-b98b-a1d31e58bb4b.png)

**Comment by gdsoumya** [comment]
@luigi-bitonti there is no need for you to use that image anymore please refer to this comment  https://github.com/litmuschaos/litmusctl/issues/45#issuecomment-977640369. You need to install all the components with the latest ci version, or you can wait for the next release where these changes are included.

**Comment by luigi-bitonti** [comment]
> @luigi-bitonti there is no need for you to use that image anymore please refer to this comment [litmuschaos/litmusctl#45 (comment)](https://github.com/litmuschaos/litmusctl/issues/45#issuecomment-977640369). You need to install all the components with the latest ci version, or you can wait for the next release where these changes are included.

I installed that image because the default image of Helm Chart Version 2.1.5 gives the error of "unknown authority".

**Comment by gdsoumya** [comment]
can you try installing using the k8s manifest directly https://github.com/litmuschaos/litmus/blob/master/litmus-portal/cluster-k8s-manifest.yml? Meanwhile, we'll take a look at the helm charts (tagging @Jonsy13  and @rajdas98 )

**Comment by Jonsy13** [comment]
Hi @luigi-bitonti `The SKIP_SSL_VERIFY : "true"` env in the helmchart is yet to be released. For testing the same now, you can use master manifest as @gdsoumya said.

**Comment by Jonsy13** [comment]
Hi @luigi-bitonti I hope the issues has been resolved. Also we have released ChaosCenter 3.x. Feel free to upgrade & let us know if issues still persists.
