### ISSUE TITLE
Update LITMUS_CORE_VERSION to v2.9.0

### ISSUE THREAD

**Issue by aslafy-z** [litmuschaos/litmus-helm#238]
Should LITMUS_CORE_VERSION be updated to v2.9.0 to work well with v2.9.0? Thank you
Same question for LITMUS_CHAOS_OPERATOR_IMAGE, LITMUS_CHAOS_RUNNER_IMAGE and LITMUS_CHAOS_EXPORTER_IMAGE

**Comment by Jasstkn** [comment]
@aslafy-z hi. what do you mean?

**Comment by aslafy-z** [comment]
I mean this image is configured with version v2.8.0: https://github.com/litmuschaos/litmus-helm/blob/9cdcdbf5acf784a238ed97f615f94a5a5c72e7c3/charts/litmus/values.yaml#L203
Shouldn't it be v2.9.0?

**Comment by Jasstkn** [comment]
> I mean this image is configured with version v2.8.0:
> 
> https://github.com/litmuschaos/litmus-helm/blob/9cdcdbf5acf784a238ed97f615f94a5a5c72e7c3/charts/litmus/values.yaml#L203
> 
> 
> Shouldn't it be v2.9.0?

Hey @Jonsy13. Maybe you can help with this question?

**Comment by Jonsy13** [comment]
Hi @aslafy-z, 

Currently, We are following step release only for having proper compatibility between core components and chaoscenter components. So Core components (exporter/operator/runner) always take previous release tag & same goes for envs like `LITMUS_CORE_VERSION` & `HUB_BRANCH_NAME`. 

If you want to use 2.9.0, you can surely update in your personal values.yaml and try it out.

**Comment by aslafy-z** [comment]
Thank you @Jonsy13. It might be interesting to add this answer to the documentation / the values.yaml comments.

**Comment by Jonsy13** [comment]
Sure @aslafy-z, We will surely try to document it in a better way.
