### ISSUE TITLE
Allow specifying DB_URL instead of DB_SERVER and DB_PORT

### ISSUE THREAD

**Issue by aslafy-z** [litmuschaos/litmus-helm#244]
When working with managed database, there are some cases where some additional flags needs to be added to the mongodb connection string. Some other can require the usage of multiple host. There should be a way to allow the use of a custom database connection string.

**Comment by uditgaurav** [comment]
Hi [aslafy-z](https://github.com/aslafy-z) We already have this capability now. Please refer the [README.md](https://github.com/litmuschaos/litmus-helm/tree/master/charts/litmus#values) to know more. Feel free to reopen in case you have any thoughts.

Thanks
