### ISSUE TITLE
Litmus front-end configmap custom changes

### ISSUE THREAD

**Issue by raja4dev** [litmuschaos/litmus-helm#245]
We have frontend configmap and could see [default.conf](https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/controlplane-configs.yaml#L29) not templated , there is nothing we can configure .

Can you accept the changes that we perform
or can you allow us to put additional custom configuration, so we don't have to perform the configuration at Kubernetes level . So that we can check them directly in the values file.
References : https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/controlplane-configs.yaml

**Comment by uditgaurav** [comment]
Hi @raja4dev , What are the items you want to templatize in default.conf?

I can see some components are already templated  as part of [3.x](https://github.com/litmuschaos/litmus-helm/blob/3c81fe14d1d252098826f141dd097b7b04b522a0/charts/litmus/templates/controlplane-configs.yaml#L91) release

Feel free to reopen in case if you have any thoughts. Thanks!
