### ISSUE TITLE
[BUG] Default ingress configuration does not match to default deployment

### ISSUE THREAD

**Issue by dabogee** [litmuschaos/litmus-helm#255]
Ingress configuration instantiates the following rules (when values.ingress.enabled=true)

Host: my-host-name

Path: /(.*)
Link: http://my-host-name/(.*)
Backends: litmusportal-frontend-service:9091/backend/(.*)

Path: /backend/(.*)
Link: http://my-host-name/backend/(.*)
Backends: litmusportal-server-service:9002/backend/(.*)

But helm chart configures the following pods:

ReplicaSet [litmusportal-frontend-84b4986f48]
ReplicaSet [litmusportal-server-5c9965fbc]

As you see there is not match between names which leads to 404 error

**Comment by Jasstkn** [comment]
Hello @dabogee. Backends are pointing to the objects with kind Service. Could you run the following command and check if they exist in the namespace? 
```
kubectl get svc
```

**Comment by dabogee** [comment]
NAME                               TYPE        EXTERNAL-IP   PORT(S)             AGE
litmusportal-auth-server-service   ClusterIP       <none>        9003/TCP,3030/TCP   5m48s
litmusportal-frontend-service      ClusterIP   <none>        9091/TCP            5m48s
litmusportal-headless-mongo        ClusterIP   <none>        27017/TCP           5m48s
litmusportal-mongo                 ClusterIP   <none>        27017/TCP           5m48s
litmusportal-server-service        ClusterIP  <none>        9002/TCP,8000/TCP   5m48s

@Jasstkn hello! there is an output

**Comment by dabogee** [comment]
There is my manifest

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litmusportal
  namespace: litmus
  annotations:
    fluxcd.io/automated: "true"
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: litmus
      version: "2.11.0"
      sourceRef:
        kind: HelmRepository
        name: litmuschaos
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      name: litmus-ingress
      host:
        name: chaos-center-v2.kube.private
        paths:
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /$1
          frontend: /(.*)
          backend: /backend/(.*)

**Comment by Jasstkn** [comment]
> There is my manifest
> 
> ```
> ---
> apiVersion: helm.toolkit.fluxcd.io/v2beta1
> kind: HelmRelease
> metadata:
>   name: litmusportal
>   namespace: litmus
>   annotations:
>     fluxcd.io/automated: "true"
> spec:
>   interval: 1m
>   timeout: 5m
>   chart:
>     spec:
>       chart: litmus
>       version: "2.11.0"
>       sourceRef:
>         kind: HelmRepository
>         name: litmuschaos
>         namespace: flux-system
>       interval: 1m
>   values:
>     ingress:
>       enabled: true
>       name: litmus-ingress
>       host:
>         name: chaos-center-v2.kube.private
>         paths:
>           annotations:
>             nginx.ingress.kubernetes.io/rewrite-target: /$1
>           frontend: /(.*)
>           backend: /backend/(.*)
> ```
> 
> when it's applied then I see 404 error but pods, services, ingress are in place and when I add the following config for ingress and disable ingress via values
> 
> ```
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   annotations:
>     nginx.ingress.kubernetes.io/rewrite-target: /$1
>   name: litmus-ingress
>   namespace: litmus
> spec:
>   rules:
>     - host: chaos-center-v2.kube.private
>       http:
>         paths:
>           - backend:
>               service:
>                 name: litmusportal-frontend-service
>                 port:
>                   number: 9091
>             path: /(.*)
>             pathType: ImplementationSpecific
>           - backend:
>               service:
>                 name: litmusportal-server-service
>                 port:
>                   number: 9002
>             path: /backend/(.*)
>             pathType: ImplementationSpecific
> ```
> 
> it starts to work

Could you show what is the ingress object for deployed HelmRelease with those values?

```
kubectl describe ingress litmusportal
```

**Comment by dabogee** [comment]
```
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             litmus-ingress
Labels:           app.kubernetes.io/component=litmus-frontend
                  app.kubernetes.io/instance=litmusportal
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=litmus
                  app.kubernetes.io/part-of=litmus
                  app.kubernetes.io/version=2.11.0
                  helm.sh/chart=litmus-2.11.0
                  helm.toolkit.fluxcd.io/name=litmusportal
                  helm.toolkit.fluxcd.io/namespace=litmus
                  litmuschaos.io/version=2.11.0
Namespace:        litmus
Address:          10.00.00.42
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                          Path  Backends
  ----                          ----  --------
  chaos-center-v2.kube.private  
                                /(.*)           litmusportal-frontend-service:9091 (10.00.00.150:8080)
                                /backend/(.*)   litmusportal-server-service:9002 (10.00.00.197:8080)
Annotations:                    field.cattle.io/publicEndpoints:
                                  [{"addresses":["10.00.00.42"],"port":80,"protocol":"HTTP","serviceName":"litmus:litmusportal-frontend-service","ingressName":"litmus:litm...
                                meta.helm.sh/release-name: litmusportal
                                meta.helm.sh/release-namespace: litmus
Events:                         <none>
```

@Jasstkn hi!

**Comment by dabogee** [comment]
When this configuration is added
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: litmus-ingress
  namespace: litmus
spec:
  rules:
    - host: chaos-center-v3.kube.private
      http:
        paths:
          - backend:
              service:
                name: litmusportal-frontend-service
                port:
                  number: 9091
            path: /(.*)
            pathType: ImplementationSpecific
          - backend:
              service:
                name: litmusportal-server-service
                port:
                  number: 9002
            path: /backend/(.*)
            pathType: ImplementationSpecific

```

it starts working and the following output is able

```
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             litmus-ingress
Labels:           kustomize.toolkit.fluxcd.io/name=flux-system
                  kustomize.toolkit.fluxcd.io/namespace=flux-system
Namespace:        litmus
Address:          10.43.220.42
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                          Path  Backends
  ----                          ----  --------
  chaos-center-v3.kube.private  
                                /(.*)           litmusportal-frontend-service:9091 (10.00.00.150:8080)
                                /backend/(.*)   litmusportal-server-service:9002 (10.00.00.129:8080)
Annotations:                    field.cattle.io/publicEndpoints:
                                  [{"addresses":["10.43.220.42"],"port":80,"protocol":"HTTP","serviceName":"litmus:litmusportal-frontend-service","ingressName":"litmus:litm...
                                nginx.ingress.kubernetes.io/rewrite-target: /$1
Events:
  Type    Reason  Age                  From                      Message
  ----    ------  ----                 ----                      -------
  Normal  Sync    7m48s (x5 over 42m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    7m48s (x5 over 42m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    7m48s (x5 over 42m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    7m48s (x5 over 42m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    7m48s (x5 over 42m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    7m48s (x5 over 42m)  nginx-ingress-controller  Scheduled for sync
  Normal  Sync    7m48s (x5 over 42m)  nginx-ingress-controller  Scheduled for sync
```
