### ISSUE TITLE
Litmus does not honor service.type field when ingress is enabled

### ISSUE THREAD

**Issue by dchourasia** [litmuschaos/litmus-helm#256]
We are hosting litmus on an kubernetes cluster on AWS (EKS) and we want to expose an external dns for litmus in order for us to access it from outside.

We are using aws ingress controller for this (aws load balancer controller), but it expects services to be NodePort as a prerequisite for creating the application load balancer (alb) and external dns

Here is the doc mentioning this : https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/spec/
`The service, service-2048, must be of type NodePort in order for the provisioned ALB to route to it.`

But we observed that litmus forces services to be ClusterIP if ingress is enabled, it does not honor service.type fields provided in values.yaml while installing helm release when ingress is enabled.

here is link and snippet from one of the service chart:  
1. https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/frontend-svc.yaml 
2. https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/templates/server-svc.yaml
![image](https://user-images.githubusercontent.com/16337882/182145231-8915d1c3-9038-40a1-9e6e-d261e8806a2a.png)

**Comment by Jasstkn** [comment]
Nice catch. I'll fix it asap
