### ISSUE TITLE
Bitnami/mongodb is not supported on Mac M1/ Need Documentation for using external mongodb instance

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmus-helm#277]
Either we can add alternative mongoDB solution in our helm chart itself or Add some documentation around how to use an external mongoDB instance.

Reference for mongodb not working on mac M1 - https://github.com/bitnami/charts/issues/7305

**Comment by itninja-hue** [comment]
https://github.com/litmuschaos/litmus-helm/blob/master/charts/litmus/values.yaml#L21
