### ISSUE TITLE
not enough ACTIVE code/PR reviewers  

### ISSUE THREAD

**Issue by itninja-hue** [litmuschaos/litmus-helm#279]
there is many PRs staling for weeks with only 1 approval/Review ...

**Comment by Jasstkn** [comment]
@ksatchit is there any news about adding new maintainers to the helm-charts?

**Comment by ksatchit** [comment]
@Jasstkn we have received interest from some folks on this - we should at least one more maintainer added to this repo shortly.

Having said that, open to volunteers amongst recent contributors!

**Comment by Jasstkn** [comment]
@ksatchit hey. any progress here?

**Comment by uditgaurav** [comment]
Hi @itninja-hue, Thank you for raising this concern about the need for more active code and PR reviewers. We have updated the CODEOWNERS file to include additional active members from our team. This update aims to ensure more timely and efficient review processes for our pull requests and code submissions. cc: @Jasstkn @ksatchit
