### ISSUE TITLE
Add litmus-portal as a helm installed component

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus-helm#29]
- litmus portal 
- prometheus 
- Authentication

**Comment by rajdas98** [comment]
Docker images for the litmusportal
- Backend
  - litmusportal-server
  - Subscriber
    - litmusportal-igc
    - litmusportal-agent
  - litmusportal-prometheus
  - litmusportal-nginx
- Frontend
  - litmusportal-frontend

**Comment by Jasstkn** [comment]
@ksatchit @rajdas98 hello! Where I can find some instructions on how to deploy it? I'll handle helm side.

**Comment by ksatchit** [comment]
@rajdas98 will be sharing the manifests here @Jasstkn . The idea is to disable the portal by default via values until it is stable. It will be however, available as a pre-alpha entity which we will use for CI/e2e purposes. 

This might also involve creating the necessary changes in the operator manifest (alternative to helm) based install that we have been using.

**Comment by rajdas98** [comment]
Hi @Jasstkn , You can refer to this k8s manifest of litmus-portal.

**Comment by Jasstkn** [comment]
@rajdas98 what about using MongoDB as a community chart? (from bitnami or from stable in helm/charts repository).
What about Prometheus and authentication (@ksatchit mentioned that in the issue description)?

**Comment by rajdas98** [comment]
Hi @Jasstkn , Thanks for suggesting the bitnami's MongoDB. But, as per the community demand, litmus portal should be lightweight, currently MongoDB is using 176MB of memory. Not sure about how much bitnami's MongoDB will be required. If it is less we can go for it.
Can you check how much memory is used by bitnami's MongoDB?

**Comment by Jasstkn** [comment]
> Hi @Jasstkn , Thanks for suggesting the bitnami's MongoDB. But, as per the community demand, litmus portal should be lightweight, currently MongoDB is using 176MB of memory. Not sure about how much memory will be required by bitnami. If it is less we can go for it.
> Can you check how much memory is used by bitnami's MongoDB?

I'll do that. My point was about to provide MongoDB as an independent service supported by a community with numerous count of features. 
https://github.com/bitnami/charts/tree/master/bitnami/mongodb

I'll test different installations in scope of this issue.

**Comment by Jasstkn** [comment]
Resolved.
