### ISSUE TITLE
Allow to specify ingress pathType for litmus

### ISSUE THREAD

**Issue by omerlh** [litmuschaos/litmus-helm#302]
I am using ALB ingress, and for ALB I need to use `pathType: Prefix` to make ALB ingress work with multiple paths.

I'll be happy to submit a PR allowing to specify the `pathType` via the values file

**Comment by Jasstkn** [comment]
@omerlh hi! could you please specify in which charts & resources you need to make those changes? and what is the current behaviour?

**Comment by omerlh** [comment]
Yes, I am talking about `litmus` chart - the ingress for the ChaosHub. I just need to make the `pathType` configurable by the values yaml.

**Comment by Jasstkn** [comment]
Got it. Please, submit a PR then.
