### ISSUE TITLE
install-litmus-agent is failing with permissions denied error

### ISSUE THREAD

**Issue by akumar760613** [litmuschaos/litmus-helm#318]
Hi Team,

Getting below error post install-litmus-agent deploy onto k8s. Litmus-agent is installed via helm charts[`https://litmuschaos.github.io/litmus-helm/`] with version `0.1.2` and releaseName `litmus-agent`

What kind of permissions are missing ? Can someone provide some insights into how we can troubleshoot this issue? TIA

```
🚀 Start Pre install hook ... 🎉

❌ Error, cannot search if agent exist: permission_denied
```

**Comment by akumar760613** [comment]
[Jasstkn](https://github.com/Jasstkn)

**Comment by Jasstkn** [comment]
Hi @akumar760613! For some reason I haven't seen this issue that you reported. Please, report this to the community slack 🙏🏻

**Comment by uditgaurav** [comment]
Hi @akumar760613 , The error message indicates that the user do not have permission to create chaos infra. This should not be the case with some of the latest versions now. I will suggest you to try with the newer version again and let us know. 

Thanks
