### ISSUE TITLE
[litmus] Fresh install of litmus 3.0.0 fails on upgrade-agent

### ISSUE THREAD

**Issue by wrdls** [litmuschaos/litmus-helm#341]
After implementing workarounds for https://github.com/litmuschaos/litmus-helm/issues/339 and https://github.com/litmuschaos/litmus-helm/issues/340 I hit the following issue:

```
litmus-upgrade-agent-cp-1-v7sqs upgrade-agent 2023-10-09T13:58:26.707181972+02:00 {"level":"fatal","ts":1696852706.706867,"caller":"upgrade-agent/main.go:54","msg":"failed to create upgrade manager","error":"failed to get previous version data from db, error=mongo: no documents in result","stacktrace":"main.main\n\t/upgrade-agent/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```

**Comment by dwdraju** [comment]
I also had to remove the upgrade-job for getting this working. I am using mongo-atlas.

**Comment by Jonsy13** [comment]
Hi @wrdls @dwdraju The changes have been merged & released. Feel free to upgrade & let us know if the issue still persists. Thanks!!
