### ISSUE TITLE
litmus-agent has APP_VERSION hard coded as 3.0.0-beta8 in template hook-pre-install-job.yaml

### ISSUE THREAD

**Issue by nwinstel-insight** [litmuschaos/litmus-helm#352]
Currently every variable in the litmus-agent hook-pre-install-job.yaml template file is variable except APP_VERSION. 

[APP_VERSION](https://github.com/litmuschaos/litmus-helm/blob/dba4a40932e4b9b921934b6517c9860c77d80008/charts/litmus-agent/templates/hook-pre-install-job.yaml#L67) is hardcoded as 3.0.0-beta8.

![Screenshot 2023-11-21 at 11 34 28 AM](https://github.com/litmuschaos/litmus-helm/assets/105605527/a4c2d8a1-0576-44ca-8c65-65bbff5e2423)

Could this be updated to be a variable value we can override?

**Comment by Calvinaud** [comment]
Hello,
It's was the goal of this PR: https://github.com/litmuschaos/litmus-helm/pull/330

**Comment by nwinstel-insight** [comment]
@Calvinaud is there anything I can do to help get this through?

**Comment by dmcardoso** [comment]
Hi @Calvinaud are there any updates about that? We need this asap.

**Comment by Calvinaud** [comment]
Hello,
The only thing still needed is the the approval on the PR.
The forked coded is here if you need it: https://github.com/Calvinaud/litmus-helm/tree/master
I will try to reping the maintener in the PR.

**Comment by Calvinaud** [comment]
PR is merged so I suppose the issue should be considered as solved.

**Comment by Jonsy13** [comment]
Since @Calvinaud's changes have been merged already. Closing this issue, feel free to open this issue if the issue still persists. Thanks!!
