### ISSUE TITLE
Image litmuschaos.docker.scarf.sh/litmuschaos/upgrade-agent-cp:3.1.0 not found

### ISSUE THREAD

**Issue by vaitiwari** [litmuschaos/litmus-helm#367]
Upgrade job is enabled in 3.1.0 version of Litmus helm chart by default. Since the image litmuschaos.docker.scarf.sh/litmuschaos/upgrade-agent-cp:3.1.0 is not present on registry, it fails with the default setting.

**Comment by Jonsy13** [comment]
Hi @vaitiwari Thanks for raising this issue, In 3.5.0 version of helm-chart, this upgrade job is now removed. Feel free to upgrade & let us know if issues persists.
