### ISSUE TITLE
Make ClusterRole and ServiceAccount optional on the operator chart

### ISSUE THREAD

**Issue by rberrelleza** [litmuschaos/litmus-helm#37]
Today, deploying litmus, even in namespaced-mode, requires cluster admin privileges due to the need to create ClusterRoles and ClusterRoleBindings. 

It would be great if there was an option to install litmus without creating cluster-level resources, or that it allow the installer to pick an existing serviceAccount instead. 

The [openfaas chart](https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/templates/controller-rbac.yaml) is an example that follows this pattern.  I already validated that the operator is able to run without this role, as long as the serviceAccount used by the operator has the correct permissions.

**Comment by ksatchit** [comment]
Sure!! We will get this added!

**Comment by uditgaurav** [comment]
Hi @rberrelleza , This is also resolved in the latest versions. Thanks!
