### ISSUE TITLE
Publish helm chart also as an OCI package (e.g. on GHCR registry)

### ISSUE THREAD

**Issue by nlamirault** [litmuschaos/litmus-helm#391]
Could you push the packaged Helm chart also on ghcr.io, so we can pull/install the helm chart like this:
```
helm install xxxx oci://ghcr.io/xxxxxxxx --version x.y.z
```

**Comment by jongwooo** [comment]
Hi @Jonsy13
I want to take this issue. Can you please assign it to me?

**Comment by Jonsy13** [comment]
Thanks @jongwooo , Have assigned you this ticket!
