### ISSUE TITLE
Release litmus-1.11.1.tgz

### ISSUE THREAD

**Issue by ToruMakabe** [litmuschaos/litmus-helm#65]
I have evaluated node-restart experiment, but failed due to exception of go-runner 1.11.0. 
It seems go-runner 1.11.1 has released.  I would like to evaluate it, so could you release the chart? Thanks!

**Comment by ksatchit** [comment]
Sure @ToruMakabe . Thanks for the heads-up. The experiment image has been pushed to 1.11.1, but the chaos-runner in the litmus chart is yet to pushed to 1.11.1 (tracked here: https://github.com/litmuschaos/litmus-helm/pull/64). Will update you on this soon.

**Comment by ksatchit** [comment]
Currently, this test is supported/tested only on kubevirt VMs - though it should potentially work elsewhere. Tagging @jordigilh here for any clarification on setting up SSH keys/other gotchas just in case!

**Comment by Jasstkn** [comment]
@ksatchit was this issue resolved?
