### ISSUE TITLE
Update litmus CRDs

### ISSUE THREAD

**Issue by jzoric** [litmuschaos/litmus-helm#84]
Environment:

* `kind` cluster 
* litmus installed via helm (following the docs)

Issue: 

while trying to use httpProbe in an experiment chaos engine couldn't be initialized e.g
`Unable to initialize ChaosEngine, because of Update Error: ChaosEngine.litmuschaos.io \"nginx-chaos-1\" is invalid: spec.experiments.spec.probe.httpProbe/inputs.method: Invalid value: 1`

Solution:

manually edit chaosengine with `kubectl edit crd chaosengines.litmuschaos.io` to remove `maxProperties: 1` on httpProbe. Thanks to @ispeakc0de 

Conclusion and bug report:

Latest CRDs from https://litmuschaos.github.io/litmus/litmus-operator-v1.13.0.yaml and helm CRDs are not in sync. Helm CRDs needs an update. Not sure if other CRDs update sync are needed.

**Comment by ispeakc0de** [comment]
fixed by https://github.com/litmuschaos/litmus-helm/pull/83
