### ISSUE TITLE
[2.0.0-beta] ConfigMap 'litmus-portal-config' is not created on a clean deployment

### ISSUE THREAD

**Issue by mr-onion-2** [litmuschaos/litmus-helm#94]
Hi

- I cloned the repo and installed Litmus as per [docs](https://litmusdocs-beta.netlify.app/docs/litmus-install)
- Connected to the portal front end and created my first project
- < Pods created >...
- The event-tracker pod reports that the 'litmus-portal-config' configmap is missing

```
NAME                                                      READY   STATUS             RESTARTS   AGE
litmuschaos-litmus-2-0-0-beta-frontend-6bbdb89479-pbm2d   1/1     Running            0          7m38s
litmuschaos-litmus-2-0-0-beta-server-7f68d99757-nnk9l     2/2     Running            0          7m38s
litmuschaos-litmus-2-0-0-beta-mongo-0                     1/1     Running            0          7m38s
workflow-controller-5f8d8c5646-td8l5                      1/1     Running            0          7m17s
chaos-operator-ce-86c98974b9-msw8q                        1/1     Running            0          7m17s
chaos-exporter-568df7fd76-gs9tc                           1/1     Running            0          7m17s
argo-server-cd89c4579-l2wlm                               1/1     Running            0          7m17s
subscriber-6bffc4b64c-7bh2b                               0/1     CrashLoopBackOff   6          7m17s
event-tracker-7dcd96fd85-4nl46                            0/1     CrashLoopBackOff   6          7m17s
```

```
kubectl logs event-tracker-7dcd96fd85-4nl46 -n litmus
2021/03/18 10:15:10 configmaps "litmus-portal-config" not found
```

The subscriber reports the following, but I'm guessing this is a consequence of the above.
```
kubectl logs subscriber-6bffc4b64c-7bh2b -n litmus
2021/03/18 10:15:04 Go Version: go1.14.15
2021/03/18 10:15:04 Go OS/Arch: linux/amd64
2021/03/18 10:15:04 Post "http://172.27.250.23:0/query": dial tcp 172.27.250.23:0: connect: connection refused
```

**Comment by gdsoumya** [comment]
The config is only created after the subscriber connects to the server, it is generated by the subscriber.

In the above issue I can see that the subscriber was unable to connect with the server, the port mentioned there seems to be wrong. Can you describe more about your setup?

**Comment by mr-onion-2** [comment]
Hi
Ahh ok so the other way around. It's most likely something I did wrong then, although it installs fine using the manifest. 
I'll double check on my end and get back to you.

Many thanks

**Comment by mr-onion-2** [comment]
Hi Souyma

I don't see anything obviously wrong in my setup actually. My local setup is a one node cluster running K3S (v1.19.5+k3s2). 

This isn't causing me an issue personally because as I say I've installed Litmus via the manifest instead. But if you think this might be a wider issue I'll happily try some more things and send you the logs etc as required.

Cheers

**Comment by rajdas98** [comment]
Hi @mr-onion-2, As per the above information, the actual issue is due to the subscriber is not able to connect to the server. Is it possible for you to send the list of services present in your litmus namespace?
```
kubectl get svc -n litmus
```

**Comment by mr-onion-2** [comment]
Hi
Cleaned down and re-deployed :-

```
NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
litmuschaos-litmus-2-0-0-beta-mongo   ClusterIP   10.43.51.198    <none>        27017/TCP           4m13s
litmusportal-server-service           ClusterIP   10.43.116.68    <none>        9002/TCP,9003/TCP   4m13s
litmusportal-frontend-service         ClusterIP   10.43.141.92    <none>        9091/TCP            4m13s
chaos-exporter                        ClusterIP   10.43.212.165   <none>        8080/TCP            2m5s
argo-server                           ClusterIP   10.43.76.64     <none>        2746/TCP            2m5s
workflow-controller-metrics           ClusterIP   10.43.93.70     <none>        9090/TCP            2m5s
chaos-operator-metrics                ClusterIP   10.43.112.78    <none>        8383/TCP            2m

```

**Comment by mr-onion-2** [comment]
I changed the litmus server and frontend service types to NodePort as per the linked PR and that has indeed fixed it :+1:

**Comment by rajdas98** [comment]
Great @mr-onion-2. We will change the default svc type to NodePort. After that, this problem will not occur again.
