### ISSUE TITLE
[2.0.0-beta]No self-cluster when deploying with helm

### ISSUE THREAD

**Issue by johnqa** [litmuschaos/litmus-helm#96]
Hi,

When deploying the portal using the helm chart I don't have the Self-Cluster available in Targets. 

When deploying with yaml file the cluster is there.

Is there a way to fix this? Should I install litmusctl?

Thank you,
John

**Comment by rajdas98** [comment]
Hi @johnqa, Thanks for trying the litmus portal. Currently, the issue is because of the service type which is `ClusterIP` in `values.yaml`
We just merge a PR to make the default service type to `NodePort`. Can you pull the latest changes and install litmusportal again?

PR- https://github.com/litmuschaos/litmus-helm/pull/95

**Comment by johnqa** [comment]
Hi,

I found the issue. By default when logging with admin you are not in any project. After selecting the project I just made, I could see the Self Cluster.

I already updated my chart with NodePort instead of ClusterIp.

Thanks for your time,
John

**Comment by johnqa** [comment]
Not sure if related, but now after creating a workflow I cannot see it in the list of workflows, but I can see the schedule for it.

**Comment by rajdas98** [comment]
Hi @johnqa, Can you confirm the workflow type? Is it a corn workflow or normal workflow?

**Comment by johnqa** [comment]
The workflow was a custom one created by uploading a yank file.

**Comment by rajdas98** [comment]
Can you check the workflows present in your target cluster by this command?
```
kubectl get workflows -n <namepace>
```

**Comment by johnqa** [comment]
Hi, since then I unistalled the helm-chart and used the yaml file deployment.

However, I removed that deployment and reinstalled with helm chart, but this time the same workflow is visible.

I will close this issue.

Thank you,
John

**Comment by rajdas98** [comment]
Great @johnqa. Let me know, if you face any problem with the litmus portal
